### ISSUE TITLE
Empty file should be handled

### ISSUE THREAD

**Issue by saberduck** [SonarSource/sonar-go-archived#280]
Currently when generator is run on empty file it will produce no output and common engine will fail to parse it with JSON parser. It should be handled without producing error in the log.

Current stacktrace

```
 ERROR: Error analyzing file empty_line.go
    java.io.EOFException: End of input at line 1 column 1 path $
    	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
    	at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1576)
    	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
    	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:379)
    	at org.sonar.uast.Unmarshaller.readNode(Unmarshaller.java:60)
    	at org.sonar.uast.Unmarshaller.unmarshal(Unmarshaller.java:52)
    	at org.sonar.uast.UastNode.from(UastNode.java:59)
    	at org.sonar.go.plugin.UastGeneratorWrapper.createUast(UastGeneratorWrapper.java:61)
    	at org.sonar.go.plugin.GoSensor.execute(GoSensor.java:85)
```

**Comment by saberduck** [comment]
After some evaluation, I think the current way of handling it is probably the best. This is really a corner case and I don't want to overcomplicate implementation to handle it.
