### ISSUE TITLE
ERROR: Coverage import failed: Invalid go coverage, expect 'mode:' on the first line.

### ISSUE THREAD

**Issue by narendrachandrakar** [SonarSource/sonar-go-archived#336]
I am trying to run sonar scan for go source coverage.

sonar-go-plugin-1.0.0.1404.jar ----------> Golang plugin
GOMETALINTER_VERSION=2.0.5
SONARSCANNER_VERSION=3.2.0.1227

Running the following command ( in container) in Jenkins job to generate coverage and report path.

gometalinter --vendor --deadline=600s --checkstyle > report.xml
go test -coverprofile=cover.out ./...
gocov convert cover.out | gocov-xml > coverage.xml
go test -v ./... | go-junit-report > test.xml

I am running the following sonar-scan  command :
sonar-scanner -X -e \
		 -D sonar.projectKey=abc \
		 -D sonar.projectName=abc  \
		 -D sonar.projectVersion=$(CURRENT_VERSION)\
		 -D sonar.projectDescription=projectdescription \
		 -D sonar.test.reportPath=./test.xml\
		 -D sonar.sources=./ \
		 -D sonar.test=./ \
		 -D sonar.test.inclusions=**/**_test.go  \
		 -D sonar.sources.exclusions=**/**_test.go \
		 -D sonar.showProfiling=true \
		 -D sonar.coverage.dtdVerification=false \
		 -D sonar.log.level=DEBUG \
		 -D sonar.exclusions=vendor/** \
		 -D sonar.language=go \
		 -D sonar.golint.report=report.xml \
		 -D sonar.go.coverage.reportPaths=coverage.xml

sonar-scanner -v
INFO: Scanner configuration file: /usr/local/sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 3.10.0-693.21.1.el7.x86_64 amd64
go version
go version go1.10.2 linux/amd64

Able to generate coverage.xml and report.xml

cat coverage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="0.8507463" branch-rate="0" lines-covered="57" lines-valid="67" branches-covered="0" branches-valid="0" complexity="0" version="" timestamp="1534541215831">
	<packages>
		<package name="engine/pkg/abc/handler" line-rate="0.8507463" branch-rate="0" complexity="0" line-count="67" line-hits="57">
			<classes>
				<class name="-" filename="/home/jenkins/jobs/sd/engine/sprint188/builds/36/src/engine/pkg/abc/handler/handler.go" line-rate="0.96153843" branch-rate="0" complexity="0" line-count="26" line-hits="25">
					<methods>
						<method name="New" signature="" line-rate="1" branch-rate="0" complexity="0" line-count="0" line-hits="0">
			

cat test.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="3" failures="0" time="0.056" name="engine/pkg/abc/handler">
		<properties>
			<property name="go.version" value="go1.10.2"></property>
		</properties>
		<testcase classname="handler" name="TestHealthCheck" time="0.000"></testcase>
		<testcase classname="handler" name="TestNew" time="0.000"></testcase>
		<testcase classname="handler" name="TestNofitication" time="0.000"></testcase>
	</testsuite>
</testsuites>

Getting the following error logs when we added this line  -D sonar.go.coverage.reportPaths=coverage.xml, but if we add  -D sonar.coverage.reportPaths=coverage.xml we are not getting any errors, but both case we are not able to see the code coverage in sonarqube dashboard only we are able to see the report.

21:27:01.081 INFO: Sensor SonarGo [go]
21:27:01.372 DEBUG: 'cmd/consumerabc/main.go' generated metadata  with charset 'UTF-8'
21:27:01.440 DEBUG: 'cmd/front/main.go' generated metadata  with charset 'UTF-8'
21:27:01.457 DEBUG: 'pkg/abc/email/email.go' generated metadata  with charset 'UTF-8'
21:27:01.493 DEBUG: 'pkg/abc/handler/handler.go' generated metadata  with charset 'UTF-8'
21:27:01.518 DEBUG: 'pkg/abc/jira/jira.go' generated metadata  with charset 'UTF-8'

21:27:01.636 INFO: Load coverage report from '/home/jenkins/jobs/sd/engine/sprint188/builds/36/src/engine/coverage.xml'

21:27:01.638 ERROR: Coverage import failed: Invalid go coverage, expect 'mode:' on the first line.
java.io.IOException: Invalid go coverage, expect 'mode:' on the first line.
	at org.sonar.go.plugin.GoCoverageReport.parse(GoCoverageReport.java:143)
	at org.sonar.go.plugin.GoCoverageReport.saveCoverageReports(GoCoverageReport.java:67)
	at org.sonar.go.plugin.GoSensor.execute(GoSensor.java:101)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

21:27:01.638 INFO: Sensor SonarGo [go] (done) | time=557ms
21:27:01.638 INFO: Sensor SonarJavaXmlFileSensor [java]
21:27:01.640 INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=2ms
21:27:01.640 INFO: Sensor Zero Coverage Sensor
21:27:01.666 INFO: Sensor Zero Coverage Sensor (done) | time=26ms
21:27:01.666 INFO: Sensor CPD Block Indexer
21:27:01.666 DEBUG: org.sonar.scanner.cpd.deprecated.DefaultCpdBlockIndexer is used for go
21:27:01.666 DEBUG: No CpdMapping for language go
21:27:01.666 INFO: Sensor CPD Block Indexer (done) | time=0ms
21:27:01.667 INFO: SCM provider for this project is: git
21:27:01.667 INFO: 10 files to be analyzed
21:27:01.682 DEBUG: readpipe [git, --version],/usr/bin
21:27:01.689 DEBUG: readpipe may return 'git version 2.11.0'
21:27:01.689 DEBUG: remaining output:

**Comment by vilchik-elena** [comment]
Why do you convert your coverage report `gocov convert cover.out | gocov-xml > coverage.xml`? 
You probably should use `cover.out` during analysis for value of `sonar.go.coverage.reportPaths`.

P.S. Please read https://guides.github.com/features/mastering-markdown/, reading your message is challenging

**Comment by narendrachandrakar** [comment]
Thanks vilchik-elena, 
I am able to see the code coverage, removed gocov command, directly passing cover.out.
